### ISSUE TITLE
populate_short data.py: command not found

### ISSUE THREAD

**Issue by QuiqueAlfa** [Caesurus/short_volume#1]
i am stuck here, and dont really know why, it's the first time i am using python so it can be a very simple thing, some help would be appreciated :)
![image](https://user-images.githubusercontent.com/66640508/107887328-a9d8a800-6f05-11eb-9ca8-04c349637089.png)

**Comment by whispy** [comment]
You have to call `python` as part of the command (e.g. `python populate_short_data.py`). Otherwise, your shell doesn't know what you're trying to do.

**Comment by Caesurus** [comment]
That or there is a shebang, so `./populate_short_data.py -d 100` _should_ work as well (on linux)
